// Verifier Contract Generated by Zokrates
var Verifier = artifacts.require("verifier");

// Contract to verify success
var VipCheck = artifacts.require("checkVIP");

module.exports = function(deployer) {
    deployer.deploy(Verifier);
    deployer.deploy(VipCheck);
};


